%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/asternin/Documents/PhDProject.git/Music and Memory - Lucy/EdatFiles/ISC_EXP_BOLD-Part1-101-1-excel.xlsx
%    Worksheet: ISC_EXP_BOLD-Part1-101-1-excel
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/29 09:56:11

%% Import the data
[~, ~, raw] = xlsread('/Users/asternin/Documents/PhDProject.git/Music and Memory - Lucy/EdatFiles/BOLD-Part1-101-1.xlsx','BOLD-Part1-101-1');
raw = raw(3:end,[2,5,44:45,53,60,68,71,75:end]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Subject = data(:,1);
BegTime = data(:,2);
Block = data(:,3);
BigInTheCity = data(:,4);
KillingTime = data(:,5);
PeopleLikeYou = data(:,6);
Slide1FinishTime = data(:,7);
Slide1OnsetTime = data(:,8);
StonesInYourPockets = data(:,9);
Superman = data(:,10);
TakeOffNotLanding = data(:,11);
Tonopah = data(:,12);
YeahYeah = data(:,13);
%% Clear temporary variables
clearvars data raw R;
%% Concatenate variables
Data=[];
Data.Subject=Subject;
Data.BegTime=BegTime;
Data.Block=Block;
Data.BigInTheCity=BigInTheCity;
Data.KillingTime=KillingTime;
Data.PeopleLikeYou=PeopleLikeYou;
Data.Slide1FinishTime=Slide1FinishTime;
Data.Slide1OnsetTime=Slide1OnsetTime;
Data.StonesInYourPockets=StonesInYourPockets;
Data.Superman=Superman;
Data.TakeOffNotLanding=TakeOffNotLanding;
Data.Tonopah=Tonopah;
Data.YeahYeah=YeahYeah;
%% Remove ITI Lines
iti=isnan(Data.Slide1OnsetTime);
Data.Subject(iti==1,:)=[];
Data.BegTime(iti==1,:)=[];
Data.Block(iti==1,:)=[];
Data.BigInTheCity(iti==1,:)=[];
Data.KillingTime(iti==1,:)=[];
Data.PeopleLikeYou(iti==1,:)=[];
Data.Slide1FinishTime(iti==1,:)=[];
Data.Slide1OnsetTime(iti==1,:)=[];
Data.StonesInYourPockets(iti==1,:)=[];
Data.Superman(iti==1,:)=[];
Data.TakeOffNotLanding(iti==1,:)=[];
Data.Tonopah(iti==1,:)=[];
Data.YeahYeah(iti==1,:)=[];
%% Calculate Durations and Onset Times Relative to Start of Scanner
Data.Duration=minus(Data.Slide1FinishTime,Data.Slide1OnsetTime);
Data.Onset=minus(Data.Slide1OnsetTime,Data.BegTime);
%% Get stim IDs into one variable
Data.names(~isnan(Data.BigInTheCity))=92;
Data.names(~isnan(Data.KillingTime))=152;
Data.names(~isnan(Data.PeopleLikeYou))=122;
Data.names(~isnan(Data.StonesInYourPockets))=102;
Data.names(~isnan(Data.Superman))=112;
Data.names(~isnan(Data.TakeOffNotLanding))=62;
Data.names(~isnan(Data.Tonopah))=142;
Data.names(~isnan(Data.YeahYeah))=82;
%% save Names, Durations, and Onsets into a .mat for SPM
names{1}= '92'; %Big in the city
onsets{1}= (Data.Onset(find(Data.names==92)))';
durations{1} = (Data.Duration(find(Data.names==92)))';

names{2}= '152'; %Killing Time
onsets{2}= (Data.Onset(find(Data.names==152)))';
durations{2} = (Data.Duration(find(Data.names==152)))';

names{3}= '122'; %People Like You
onsets{3}= (Data.Onset(find(Data.names==122)))';
durations{3} = (Data.Duration(find(Data.names==122)))';

names{4}= '102'; %Stones In your pockets
onsets{4}= (Data.Onset(find(Data.names==102)))';
durations{4} = (Data.Duration(find(Data.names==102)))';

names{5}= '112'; %Superman
onsets{5}= (Data.Onset(find(Data.names==112)))';
durations{5} = (Data.Duration(find(Data.names==112)))';

names{6}= '62'; %Take Off not landing
onsets{6}= (Data.Onset(find(Data.names==62)))';
durations{6} = (Data.Duration(find(Data.names==62)))';

names{7}= '142'; %Tonopah
onsets{7}= (Data.Onset(find(Data.names==142)))';
durations{7} = (Data.Duration(find(Data.names==142)))';

names{8}= '82'; %People Like You
onsets{8}= (Data.Onset(find(Data.names==82)))';
durations{8} = (Data.Duration(find(Data.names==82)))';

save('Bold1.mat','names','onsets','durations');